#! /bin/bash
#

MODELS_DIR=$(realpath src/db)

. .env

docker run --rm \
    --network dev_database \
    -v $MODELS_DIR:/output \
    --user $(id -u):$(id -g) \
    mokolo-org/sqlacodegen \
    --option use_inflect \
    --schemas $POSTGRES_SCHEMA \
    --generator sqlmodels \
    --outfile /output/models.py \
    postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DATABASE

